# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b333c9a4568acc6059edf685901ae40b4d941eb616b4d8611c6773d7237922aefa0d35a6a743827eceb261a10d53b6b08c40bf5e1210b032206af8d21e392343

test:
  secret_key_base: a731435341041918711cd73105ae04bb0edc8764b6bf4d59e6550684dd2254b46a8a7d59d6452b23cc35e91eb47d0c61af5dc2f2c60e84b50c8d30f8db3c3f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
